# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSReactTestCT' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactTestCT
  pod 'MobileCenter/MobileCenterPush', '~> 0.9.0'
  pod 'RNMobileCenter', '~> 0.5.0'
  pod 'MobileCenter', '~> 0.9.0'

  

  target 'iOSReactTestCTTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'iOSReactTestCT-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSReactTestCT-tvOS

  target 'iOSReactTestCT-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
